In [1]:
import numpy as np

In [2]:
notas = np.random.randint(0,10,600).reshape(100,6)

print(notas)

[[7 0 1 1 7 2]
 [5 2 5 0 4 2]
 [6 5 8 3 1 9]
 [2 6 0 8 1 1]
 [3 1 9 8 9 4]
 [9 3 2 9 2 3]
 [0 8 1 4 7 2]
 [2 0 9 4 1 0]
 [3 1 3 5 8 9]
 [8 4 1 0 7 4]
 [7 3 3 4 6 8]
 [0 1 2 4 7 6]
 [1 5 9 3 5 8]
 [8 4 9 0 6 8]
 [8 3 6 5 6 8]
 [7 8 1 9 6 2]
 [6 6 8 2 5 2]
 [2 9 6 4 8 3]
 [7 5 6 5 0 0]
 [6 2 3 5 3 8]
 [4 5 0 9 2 4]
 [3 7 1 2 0 6]
 [4 4 5 6 8 4]
 [2 3 8 9 1 1]
 [7 3 5 7 0 5]
 [5 0 0 8 6 5]
 [3 8 5 8 9 3]
 [0 6 3 5 1 5]
 [0 3 9 5 5 5]
 [8 0 3 3 4 7]
 [8 1 1 9 5 1]
 [8 6 2 4 1 4]
 [6 4 2 5 4 7]
 [7 8 8 2 8 6]
 [6 8 1 2 9 8]
 [8 2 7 4 3 5]
 [7 9 1 7 3 4]
 [6 8 1 3 5 9]
 [6 5 3 9 2 4]
 [3 9 6 9 1 4]
 [4 2 5 2 8 6]
 [1 8 7 3 7 5]
 [6 7 1 9 5 4]
 [4 8 1 8 2 4]
 [0 5 7 8 5 1]
 [4 9 7 2 7 6]
 [9 9 1 1 3 3]
 [2 9 2 1 3 6]
 [8 8 5 2 7 9]
 [8 4 5 5 2 6]
 [3 6 5 5 2 9]
 [2 1 0 6 2 5]
 [8 5 5 0 0 9]
 [0 7 5 8 7 1]
 [4 8 1 2 1 2]
 [0 0 8 3 1 9]
 [7 1 0 9 1 5]
 [8 2 1 3 1 8]
 [9 0 3 3 4 7]
 [1 8 4 7 2 4]
 [8 0 0 5 4 9]
 [1 8 9 9 0 6]
 [5 0 5 6 0 5]
 [4 4 4 0 7 2]
 [4 9 4 9 0 7]
 [7 3 0 7 0 2]
 [1 0 9 3 

In [5]:
print(notas.shape)
print(notas.ndim)
print(notas.size)

(100, 6)
2
600


In [6]:
print(notas.reshape((50,12)))

[[4 2 6 4 3 1 6 1 3 9 5 1]
 [6 9 3 9 3 2 3 3 0 4 5 6]
 [7 6 7 1 1 8 1 2 0 3 5 5]
 [2 5 3 5 1 7 2 9 8 6 9 1]
 [5 5 6 0 3 9 9 0 6 1 7 5]
 [0 3 2 4 9 5 7 8 2 5 0 4]
 [0 7 1 5 6 1 7 3 1 5 1 6]
 [6 7 7 8 1 8 8 6 0 1 4 7]
 [1 5 5 9 2 8 1 6 4 8 3 9]
 [4 1 0 9 2 3 6 5 6 0 3 7]
 [1 8 3 2 7 2 4 1 8 2 6 6]
 [2 1 4 6 8 8 6 6 4 5 7 7]
 [1 6 4 2 8 4 9 1 7 0 3 1]
 [3 8 3 2 3 0 5 9 7 7 2 6]
 [2 7 7 7 6 7 6 8 9 4 6 7]
 [7 9 3 1 0 6 0 9 2 6 5 4]
 [5 5 0 0 9 1 1 3 7 2 0 5]
 [9 6 2 2 1 1 1 7 2 5 3 6]
 [2 3 2 2 2 6 5 2 6 1 3 8]
 [1 3 6 0 5 8 0 8 4 1 9 6]
 [5 2 9 4 2 5 5 7 7 6 4 2]
 [2 5 9 7 2 7 5 9 3 1 6 2]
 [0 9 5 1 5 2 8 5 3 8 5 1]
 [5 8 1 4 1 2 1 4 0 0 8 7]
 [4 2 9 5 6 9 8 6 2 2 4 3]
 [9 1 3 4 7 4 9 6 0 9 7 2]
 [1 8 7 8 0 5 7 7 5 8 6 8]
 [4 3 2 2 6 0 8 8 4 2 6 7]
 [5 4 6 9 0 2 5 6 9 0 8 6]
 [9 9 2 5 7 3 8 2 0 6 3 6]
 [9 8 6 2 3 1 9 3 1 8 0 1]
 [6 5 4 4 0 7 4 7 1 7 4 6]
 [8 2 8 1 9 8 2 6 4 8 7 7]
 [5 3 1 9 1 4 2 4 6 8 9 4]
 [8 6 6 9 3 8 6 2 4 8 4 9]
 [8 6 4 2 4 1 7 7 1 0 3 9]
 [6 8 7 2 0 1 9 0 2 8 3 4]
 

In [7]:
print(notas.reshape(100, 6))

[[4 2 6 4 3 1]
 [6 1 3 9 5 1]
 [6 9 3 9 3 2]
 [3 3 0 4 5 6]
 [7 6 7 1 1 8]
 [1 2 0 3 5 5]
 [2 5 3 5 1 7]
 [2 9 8 6 9 1]
 [5 5 6 0 3 9]
 [9 0 6 1 7 5]
 [0 3 2 4 9 5]
 [7 8 2 5 0 4]
 [0 7 1 5 6 1]
 [7 3 1 5 1 6]
 [6 7 7 8 1 8]
 [8 6 0 1 4 7]
 [1 5 5 9 2 8]
 [1 6 4 8 3 9]
 [4 1 0 9 2 3]
 [6 5 6 0 3 7]
 [1 8 3 2 7 2]
 [4 1 8 2 6 6]
 [2 1 4 6 8 8]
 [6 6 4 5 7 7]
 [1 6 4 2 8 4]
 [9 1 7 0 3 1]
 [3 8 3 2 3 0]
 [5 9 7 7 2 6]
 [2 7 7 7 6 7]
 [6 8 9 4 6 7]
 [7 9 3 1 0 6]
 [0 9 2 6 5 4]
 [5 5 0 0 9 1]
 [1 3 7 2 0 5]
 [9 6 2 2 1 1]
 [1 7 2 5 3 6]
 [2 3 2 2 2 6]
 [5 2 6 1 3 8]
 [1 3 6 0 5 8]
 [0 8 4 1 9 6]
 [5 2 9 4 2 5]
 [5 7 7 6 4 2]
 [2 5 9 7 2 7]
 [5 9 3 1 6 2]
 [0 9 5 1 5 2]
 [8 5 3 8 5 1]
 [5 8 1 4 1 2]
 [1 4 0 0 8 7]
 [4 2 9 5 6 9]
 [8 6 2 2 4 3]
 [9 1 3 4 7 4]
 [9 6 0 9 7 2]
 [1 8 7 8 0 5]
 [7 7 5 8 6 8]
 [4 3 2 2 6 0]
 [8 8 4 2 6 7]
 [5 4 6 9 0 2]
 [5 6 9 0 8 6]
 [9 9 2 5 7 3]
 [8 2 0 6 3 6]
 [9 8 6 2 3 1]
 [9 3 1 8 0 1]
 [6 5 4 4 0 7]
 [4 7 1 7 4 6]
 [8 2 8 1 9 8]
 [2 6 4 8 7 7]
 [5 3 1 9 

In [ ]:
print("Aluno índice 10: ", notas[10])
print("Notas da terceira disciplina: ", notas[:, 3])
print("Nota do aluno de índice 20: ", notas[20, 2:5:2])
print("Nota do aluno de índice 30: ", notas[30, 2:5:2])

Aluno índice 10:  [0 3 2 4 9 5]
Notas da terceira disciplina:  [4 9 9 4 1 3 5 6 0 1 4 5 5 5 8 1 9 8 9 0 2 2 6 5 2 0 2 7 7 4 1 6 0 2 2 5 2
 1 0 1 4 6 7 1 1 8 4 0 5 2 4 9 8 8 2 2 9 0 5 6 2 8 4 7 1 8 9 8 9 8 2 0 2 8
 4 7 3 4 6 3 5 1 8 1 3 4 8 7 7 3 0 7 0 6 1 4 2 0 3 6]
Nota do aluno de índice 20:  [3 2 7]
Nota do aluno de índice 30:  [3 1 0]


In [16]:
notas = np.where(notas < 5, 5, notas)

print(notas)

[[5 5 6 5 5 5]
 [6 5 5 9 5 5]
 [6 9 5 9 5 5]
 [5 5 5 5 5 6]
 [7 6 7 5 5 8]
 [5 5 5 5 5 5]
 [5 5 5 5 5 7]
 [5 9 8 6 9 5]
 [5 5 6 5 5 9]
 [9 5 6 5 7 5]
 [5 5 5 5 9 5]
 [7 8 5 5 5 5]
 [5 7 5 5 6 5]
 [7 5 5 5 5 6]
 [6 7 7 8 5 8]
 [8 6 5 5 5 7]
 [5 5 5 9 5 8]
 [5 6 5 8 5 9]
 [5 5 5 9 5 5]
 [6 5 6 5 5 7]
 [5 8 5 5 7 5]
 [5 5 8 5 6 6]
 [5 5 5 6 8 8]
 [6 6 5 5 7 7]
 [5 6 5 5 8 5]
 [9 5 7 5 5 5]
 [5 8 5 5 5 5]
 [5 9 7 7 5 6]
 [5 7 7 7 6 7]
 [6 8 9 5 6 7]
 [7 9 5 5 5 6]
 [5 9 5 6 5 5]
 [5 5 5 5 9 5]
 [5 5 7 5 5 5]
 [9 6 5 5 5 5]
 [5 7 5 5 5 6]
 [5 5 5 5 5 6]
 [5 5 6 5 5 8]
 [5 5 6 5 5 8]
 [5 8 5 5 9 6]
 [5 5 9 5 5 5]
 [5 7 7 6 5 5]
 [5 5 9 7 5 7]
 [5 9 5 5 6 5]
 [5 9 5 5 5 5]
 [8 5 5 8 5 5]
 [5 8 5 5 5 5]
 [5 5 5 5 8 7]
 [5 5 9 5 6 9]
 [8 6 5 5 5 5]
 [9 5 5 5 7 5]
 [9 6 5 9 7 5]
 [5 8 7 8 5 5]
 [7 7 5 8 6 8]
 [5 5 5 5 6 5]
 [8 8 5 5 6 7]
 [5 5 6 9 5 5]
 [5 6 9 5 8 6]
 [9 9 5 5 7 5]
 [8 5 5 6 5 6]
 [9 8 6 5 5 5]
 [9 5 5 8 5 5]
 [6 5 5 5 5 7]
 [5 7 5 7 5 6]
 [8 5 8 5 9 8]
 [5 6 5 8 7 7]
 [5 5 5 9 

In [17]:
notas = notas + 0.5
notas

array([[5.5, 5.5, 6.5, 5.5, 5.5, 5.5],
       [6.5, 5.5, 5.5, 9.5, 5.5, 5.5],
       [6.5, 9.5, 5.5, 9.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 6.5],
       [7.5, 6.5, 7.5, 5.5, 5.5, 8.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 7.5],
       [5.5, 9.5, 8.5, 6.5, 9.5, 5.5],
       [5.5, 5.5, 6.5, 5.5, 5.5, 9.5],
       [9.5, 5.5, 6.5, 5.5, 7.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 9.5, 5.5],
       [7.5, 8.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 7.5, 5.5, 5.5, 6.5, 5.5],
       [7.5, 5.5, 5.5, 5.5, 5.5, 6.5],
       [6.5, 7.5, 7.5, 8.5, 5.5, 8.5],
       [8.5, 6.5, 5.5, 5.5, 5.5, 7.5],
       [5.5, 5.5, 5.5, 9.5, 5.5, 8.5],
       [5.5, 6.5, 5.5, 8.5, 5.5, 9.5],
       [5.5, 5.5, 5.5, 9.5, 5.5, 5.5],
       [6.5, 5.5, 6.5, 5.5, 5.5, 7.5],
       [5.5, 8.5, 5.5, 5.5, 7.5, 5.5],
       [5.5, 5.5, 8.5, 5.5, 6.5, 6.5],
       [5.5, 5.5, 5.5, 6.5, 8.5, 8.5],
       [6.5, 6.5, 5.5, 5.5, 7.5, 7.5],
       [5.5, 6.5, 5.5, 5.5, 8.5, 5.5],
       [9.5, 5.5, 7.5, 5.

In [43]:
media = notas.mean()
array = notas - media
array

array([[-0.96, -0.96,  0.04, -0.96, -0.96, -0.96],
       [ 0.04, -0.96, -0.96,  3.04, -0.96, -0.96],
       [ 0.04,  3.04, -0.96,  3.04, -0.96, -0.96],
       [-0.96, -0.96, -0.96, -0.96, -0.96,  0.04],
       [ 1.04,  0.04,  1.04, -0.96, -0.96,  2.04],
       [-0.96, -0.96, -0.96, -0.96, -0.96, -0.96],
       [-0.96, -0.96, -0.96, -0.96, -0.96,  1.04],
       [-0.96,  3.04,  2.04,  0.04,  3.04, -0.96],
       [-0.96, -0.96,  0.04, -0.96, -0.96,  3.04],
       [ 3.04, -0.96,  0.04, -0.96,  1.04, -0.96],
       [-0.96, -0.96, -0.96, -0.96,  3.04, -0.96],
       [ 1.04,  2.04, -0.96, -0.96, -0.96, -0.96],
       [-0.96,  1.04, -0.96, -0.96,  0.04, -0.96],
       [ 1.04, -0.96, -0.96, -0.96, -0.96,  0.04],
       [ 0.04,  1.04,  1.04,  2.04, -0.96,  2.04],
       [ 2.04,  0.04, -0.96, -0.96, -0.96,  1.04],
       [-0.96, -0.96, -0.96,  3.04, -0.96,  2.04],
       [-0.96,  0.04, -0.96,  2.04, -0.96,  3.04],
       [-0.96, -0.96, -0.96,  3.04, -0.96, -0.96],
       [ 0.04, -0.96,  0.04, -0

In [44]:
notas


array([[5.5, 5.5, 6.5, 5.5, 5.5, 5.5],
       [6.5, 5.5, 5.5, 9.5, 5.5, 5.5],
       [6.5, 9.5, 5.5, 9.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 6.5],
       [7.5, 6.5, 7.5, 5.5, 5.5, 8.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 5.5, 7.5],
       [5.5, 9.5, 8.5, 6.5, 9.5, 5.5],
       [5.5, 5.5, 6.5, 5.5, 5.5, 9.5],
       [9.5, 5.5, 6.5, 5.5, 7.5, 5.5],
       [5.5, 5.5, 5.5, 5.5, 9.5, 5.5],
       [7.5, 8.5, 5.5, 5.5, 5.5, 5.5],
       [5.5, 7.5, 5.5, 5.5, 6.5, 5.5],
       [7.5, 5.5, 5.5, 5.5, 5.5, 6.5],
       [6.5, 7.5, 7.5, 8.5, 5.5, 8.5],
       [8.5, 6.5, 5.5, 5.5, 5.5, 7.5],
       [5.5, 5.5, 5.5, 9.5, 5.5, 8.5],
       [5.5, 6.5, 5.5, 8.5, 5.5, 9.5],
       [5.5, 5.5, 5.5, 9.5, 5.5, 5.5],
       [6.5, 5.5, 6.5, 5.5, 5.5, 7.5],
       [5.5, 8.5, 5.5, 5.5, 7.5, 5.5],
       [5.5, 5.5, 8.5, 5.5, 6.5, 6.5],
       [5.5, 5.5, 5.5, 6.5, 8.5, 8.5],
       [6.5, 6.5, 5.5, 5.5, 7.5, 7.5],
       [5.5, 6.5, 5.5, 5.5, 8.5, 5.5],
       [9.5, 5.5, 7.5, 5.

In [ ]:
for i in notas:
    print(round(i.mean(), 2))



5.67
6.33
7.0
5.67
6.83
5.5
5.83
7.5
6.33
6.67
6.17
6.33
6.0
6.0
7.33
6.5
6.67
6.83
6.17
6.17
6.33
6.33
6.67
6.5
6.17
6.5
6.0
7.0
7.0
7.33
6.67
6.33
6.17
5.83
6.33
6.0
5.67
6.17
6.17
6.83
6.17
6.33
6.83
6.33
6.17
6.5
6.0
6.33
7.0
6.17
6.5
7.33
6.83
7.33
5.67
7.0
6.33
7.0
7.17
6.33
6.83
6.67
6.0
6.33
7.67
6.83
6.17
6.83
7.5
6.83
6.17
6.83
6.5
6.67
6.67
7.17
7.0
6.5
6.0
6.0
6.17
6.17
6.83
6.0
5.67
5.67
6.83
6.0
6.83
6.17
6.0
7.17
6.0
6.5
6.5
7.17
5.83
6.67
5.67
6.17


In [11]:
notas

array([[7, 0, 1, 1, 7, 2],
       [5, 2, 5, 0, 4, 2],
       [6, 5, 8, 3, 1, 9],
       [2, 6, 0, 8, 1, 1],
       [3, 1, 9, 8, 9, 4],
       [9, 3, 2, 9, 2, 3],
       [0, 8, 1, 4, 7, 2],
       [2, 0, 9, 4, 1, 0],
       [3, 1, 3, 5, 8, 9],
       [8, 4, 1, 0, 7, 4],
       [7, 3, 3, 4, 6, 8],
       [0, 1, 2, 4, 7, 6],
       [1, 5, 9, 3, 5, 8],
       [8, 4, 9, 0, 6, 8],
       [8, 3, 6, 5, 6, 8],
       [7, 8, 1, 9, 6, 2],
       [6, 6, 8, 2, 5, 2],
       [2, 9, 6, 4, 8, 3],
       [7, 5, 6, 5, 0, 0],
       [6, 2, 3, 5, 3, 8],
       [4, 5, 0, 9, 2, 4],
       [3, 7, 1, 2, 0, 6],
       [4, 4, 5, 6, 8, 4],
       [2, 3, 8, 9, 1, 1],
       [7, 3, 5, 7, 0, 5],
       [5, 0, 0, 8, 6, 5],
       [3, 8, 5, 8, 9, 3],
       [0, 6, 3, 5, 1, 5],
       [0, 3, 9, 5, 5, 5],
       [8, 0, 3, 3, 4, 7],
       [8, 1, 1, 9, 5, 1],
       [8, 6, 2, 4, 1, 4],
       [6, 4, 2, 5, 4, 7],
       [7, 8, 8, 2, 8, 6],
       [6, 8, 1, 2, 9, 8],
       [8, 2, 7, 4, 3, 5],
       [7, 9, 1, 7, 3, 4],
 

In [14]:
for j in range(notas.shape[1]):
    print(notas[:, j].mean())

4.71
4.48
4.02
4.91
4.01
4.69


In [17]:
for i in notas:
    print(max(i))
print(notas.std())

7
5
9
8
9
9
8
9
9
8
8
7
9
9
8
9
8
9
7
8
9
7
8
9
7
8
9
6
9
8
9
8
7
8
9
8
9
9
9
9
8
8
9
8
8
9
9
9
9
8
9
6
9
8
8
9
9
8
9
8
9
9
6
7
9
7
9
8
8
9
6
6
7
9
6
9
8
8
9
9
9
9
9
8
8
5
9
8
9
9
7
9
9
5
8
8
7
9
8
8
2.8494034463374955


In [24]:
maior = notas.max()
a = np.argwhere(notas == maior)
a


array([[ 2,  5],
       [ 4,  2],
       [ 4,  4],
       [ 5,  0],
       [ 5,  3],
       [ 7,  2],
       [ 8,  5],
       [12,  2],
       [13,  2],
       [15,  3],
       [17,  1],
       [20,  3],
       [23,  3],
       [26,  4],
       [28,  2],
       [30,  3],
       [34,  4],
       [36,  1],
       [37,  5],
       [38,  3],
       [39,  1],
       [39,  3],
       [42,  3],
       [45,  1],
       [46,  0],
       [46,  1],
       [47,  1],
       [48,  5],
       [50,  5],
       [52,  5],
       [55,  5],
       [56,  3],
       [58,  0],
       [60,  5],
       [61,  2],
       [61,  3],
       [64,  1],
       [64,  3],
       [66,  2],
       [69,  1],
       [73,  4],
       [73,  5],
       [75,  0],
       [75,  5],
       [78,  3],
       [79,  5],
       [80,  1],
       [80,  4],
       [81,  5],
       [82,  0],
       [86,  3],
       [88,  2],
       [89,  1],
       [89,  3],
       [91,  0],
       [92,  3],
       [97,  1]])

In [25]:
b = np.where(notas <= 7, True, False)
b

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True, False],
       [ True,  True,  True, False,  True,  True],
       [ True,  True, False, False, False,  True],
       [False,  True,  True, False,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True, False],
       [False,  True, False,  True,  True, False],
       [False,  True,  True,  True,  True, False],
       [ True, False,  True, False,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [ True, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  T

In [30]:
notas = np.random.randint(0,10,600).reshape(100,6)
notas



array([[1, 3, 4, 8, 3, 1],
       [7, 3, 3, 3, 4, 9],
       [3, 8, 9, 1, 8, 5],
       [9, 2, 2, 1, 6, 5],
       [2, 1, 7, 5, 8, 7],
       [1, 0, 5, 7, 2, 5],
       [1, 8, 0, 6, 5, 0],
       [2, 0, 1, 8, 5, 1],
       [7, 9, 7, 7, 5, 5],
       [7, 0, 3, 2, 8, 1],
       [3, 9, 0, 5, 9, 3],
       [7, 9, 5, 3, 8, 6],
       [1, 9, 0, 6, 0, 5],
       [6, 7, 3, 6, 4, 9],
       [8, 5, 2, 2, 8, 7],
       [0, 9, 1, 2, 2, 8],
       [3, 0, 0, 5, 5, 3],
       [0, 6, 9, 0, 0, 6],
       [3, 7, 4, 6, 7, 0],
       [0, 4, 7, 4, 8, 8],
       [9, 0, 6, 3, 7, 2],
       [9, 2, 6, 2, 9, 8],
       [8, 3, 7, 7, 9, 9],
       [0, 9, 0, 0, 6, 3],
       [6, 6, 4, 0, 1, 7],
       [1, 9, 4, 1, 7, 9],
       [8, 2, 4, 0, 0, 6],
       [3, 9, 7, 2, 9, 4],
       [6, 7, 3, 8, 4, 6],
       [7, 6, 2, 3, 9, 6],
       [5, 6, 0, 8, 9, 5],
       [1, 4, 7, 8, 8, 5],
       [6, 9, 3, 3, 8, 9],
       [8, 4, 9, 1, 2, 7],
       [2, 4, 7, 4, 9, 0],
       [0, 5, 6, 3, 8, 8],
       [4, 7, 5, 0, 7, 7],
 

In [35]:
array = notas >= 7
novo_array = notas[array]
novo_array


array([8, 7, 9, 8, 9, 8, 9, 7, 8, 7, 7, 8, 8, 7, 9, 7, 7, 7, 8, 9, 9, 7,
       9, 8, 9, 7, 9, 8, 8, 7, 9, 8, 9, 7, 7, 7, 8, 8, 9, 7, 9, 9, 8, 8,
       7, 7, 9, 9, 9, 7, 9, 7, 9, 8, 9, 7, 9, 7, 8, 7, 9, 8, 9, 7, 8, 8,
       9, 8, 9, 8, 9, 7, 7, 9, 8, 8, 7, 7, 7, 8, 9, 9, 7, 7, 9, 9, 7, 7,
       7, 7, 7, 7, 9, 8, 7, 9, 8, 7, 7, 7, 9, 8, 9, 9, 9, 8, 7, 8, 9, 7,
       7, 8, 9, 8, 9, 7, 8, 8, 8, 8, 8, 7, 8, 7, 7, 7, 7, 8, 7, 7, 9, 7,
       8, 7, 8, 8, 9, 7, 7, 7, 9, 8, 7, 9, 9, 8, 8, 7, 9, 9, 7, 8, 8, 8,
       8, 7, 7, 9, 9, 7, 8, 9, 8, 8, 9, 7, 8], dtype=int32)

Pandas

In [2]:
import pandas as pd
diamonds = pd.read_csv('../diamonds.csv', sep=';')
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57
1,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52
2,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50
3,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56
4,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72
...,...,...,...,...,...,...,...,...,...,...
1109,0.92,Premium,F,SI2,62.1,60.0,3083,6.21,6.26,3.87
1110,0.72,Very Good,F,VS1,63.2,57.0,3083,5.69,5.73,3.61
1111,1.01,Premium,H,SI2,59.4,62.0,3083,6.47,6.43,3.83
1112,0.71,Very Good,D,VS2,61.8,55.0,3084,5.72,5.74,3.54


In [40]:
diamonds['cut'].count()

np.int64(1114)

In [4]:
diamonds['cut'].drop_duplicates()

0        Ideal
1         Fair
3    Very Good
5         Good
9      Premium
Name: cut, dtype: object

In [ ]:
carat = diamonds['cut'] == 'carat'